version: "3.8"

services:
    api:
        build: ./app
        ports: 
            - 8080:8080

        volumes:
            - ./app:/app
        restart: always
#         depends_on:
#             - db

#     db:
#         image: postgres:13.0-alpine
#         volumes:
#         - postgres_data:/var/lib/postgresql/data/
#         env_file:
#         - ./app/.env

# volumes:
#     postgres_data:

